"""
Output Formatter for NEXUS-Forecast Phase 19 Offline Inference.
Provides standardized formatting and export functions for JSON, JSONL, and SOC Markdown.
"""

import os
import json
import pandas as pd
from typing import Dict, List, Any


class OutputFormatter:
    """Formats and exports inference results."""

    @staticmethod
    def to_json(results: List[Dict[str, Any]], indent: int = 2) -> str:
        """Format results as pretty-printed JSON string."""
        if len(results) == 1:
            return json.dumps(results[0], indent=indent)
        return json.dumps(results, indent=indent)

    @staticmethod
    def save_json(results: List[Dict[str, Any]], filepath: str, indent: int = 2) -> None:
        """Save results to JSON file."""
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            if len(results) == 1:
                json.dump(results[0], f, indent=indent)
            else:
                json.dump(results, f, indent=indent)

    @staticmethod
    def save_jsonl(results: List[Dict[str, Any]], filepath: str) -> None:
        """Save results as JSON Lines."""
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            for item in results:
                f.write(json.dumps(item) + "\n")

    @staticmethod
    def to_soc_markdown(forecast: Dict[str, Any]) -> str:
        """Render a single forecast dictionary as an actionable SOC Markdown brief."""
        fid = forecast.get("forecast_id", "UNKNOWN")
        ts = forecast.get("timestamp", "")
        summary = forecast.get("summary", {})
        exec_ms = forecast.get("execution_time_ms", 0.0)

        lines = [
            f"# NEXUS-Forecast Threat Intelligence Alert: {fid}",
            f"**Timestamp**: `{ts}` | **Execution Time**: `{exec_ms} ms` | **Threat Level**: `{summary.get('threat_level', 'BENIGN')}`",
            f"**Attack Forecasted**: `{'YES - IMMEDIATE ACTION' if summary.get('overall_attack_forecasted') else 'NO - NORMAL OPERATION'}`",
            f"**Trajectory**: `{' -> '.join(summary.get('predicted_trajectory', []))}`\n",
            "---",
            "## Horizon Breakdown\n",
        ]

        horizons = forecast.get("horizons", {})
        for h_key, h_data in horizons.items():
            status = "MALICIOUS ACTIVITY DETECTED" if h_data.get("predicted_attack") else "BENIGN"
            prob = h_data.get("calibrated_attack_prob", 0.0)
            stage = h_data.get("predicted_stage", "BENIGN")
            lines.append(f"### {h_key.upper()} (+{h_data.get('horizon_seconds', 0)}s)")
            lines.append(f"- **Status**: `{status}` (Probability: **{prob:.2%}**)")
            lines.append(f"- **Stage**: `{stage}` (Confidence: **{h_data.get('stage_confidence', 0.0):.2%}**)")

            # Explanation
            expl = h_data.get("explanation")
            if expl:
                top_feats = expl.get("top_contributing_features", expl.get("top_features", []))
                lines.append(f"- **Top Influential Features**: `{', '.join(top_feats)}`")

            # Enrichment
            enrich = h_data.get("enrichment")
            if enrich and h_data.get("predicted_attack"):
                techs = enrich.get("attack_techniques", [])
                if techs:
                    lines.append("\n**Key Associated MITRE ATT&CK Techniques**:")
                    for t in techs[:5]:
                        lines.append(f"  - `{t['attack_id']}`: {t['technique']} (*{t.get('relevance', 'CONTEXTUAL')}*)")

                capecs = enrich.get("capec_patterns", [])
                if capecs:
                    lines.append("\n**Key Associated CAPEC Patterns**:")
                    for c in capecs[:5]:
                        lines.append(f"  - `{c['capec_id']}`: {c['name']} (Severity: {c.get('typical_severity', 'Medium')})")

                reviews = enrich.get("unresolved_review_items", [])
                if reviews:
                    lines.append("\n> [!WARNING]")
                    lines.append(f"> **Analyst Review Required**: `{', '.join(reviews)}`")

            lines.append("\n")

        lines.append("---")
        lines.append("*Generated by NEXUS-Forecast Phase 19 Air-Gapped Inference Pipeline.*")
        return "\n".join(lines)
